# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PR-ogrammer Blog
email: "" 
description: > # this means to ignore newlines until "baseurl:"
  "Programming is like sex. One mistake and you have to support it for the rest of your life."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pr-ogrammer.gitub.io" # the base hostname & protocol for your site
github_username:  pr-ogrammer

# Build settings
markdown: kramdown
